version: 0.0
os: linux
files:
  - source: ./
    destination: /home/azureuser/app_tmp
hooks:
  #BeforeInstall:
  #  - location: scripts/aws_cd_mkdir
  #    timeout: 300
  #    runas: root
  AfterInstall:
    - location: scripts/aws_cd_mkdir
      timeout: 300
      runas: root
    - location: scripts/aws_cd_rsync
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/aws_cd_start
      timeout: 300
      runas: root
    - location: scripts/aws_cd_rmdir
      timeout: 300
      runas: root
