version: "2"

services:

  deploy:
    image: mario21ic/pydeploy:v3
    volumes:
      - ./artifact.zip:/tmp/artifact.zip
      - ./appspec.yml:/tmp/appspec.yml
      - /home/azureuser/app/:/home/azureuser/app
    command: pydeploy
