version: '3.8'

services:
  api:
    image: mario21ic/dotnet-api:v4
    ports:
      - 8081:80
    deploy:
      replicas: 3
      resources:
        limits:
          cpus: '0.50'
          memory: 512M
      restart_policy:
        condition: on-failure
    networks:
      - my-network

networks:
  my-network:
    driver: overlay

